### DISCUSSION TITLE
快速开关候选窗

### DISCUSSION THREAD

**Discussion by ksqsf** [rimeinn/rime-moran#141] [Ideas]
方法来自群友「小溪散步」。

首先，创建一个新 schema `moran_blind.schema.yaml` ，内容如下：

```yaml
__include: moran.schema:/

schema:
  schema_id: moran_blind
  name: 盲然
  dependencies:
    - moran

style:
  # For Squirrel
  alpha: 0.000001
  inline_preedit: false
  inline_candidate: true
  # For Weasel
  preedit_type: preview
  layout:
    margin_x: -1
    margin_y: -1
```

然后把 `moran_blind` 添加到 `schema_list` 中。重新部署，从选单中选择「盲然」即可。按 Control+Shift+1 可在最近的两个 schema 间切换，即若最近两个 schema 是「魔然」和「盲然」，就可以用这个快捷键快速切换是否显示候选窗了。
