### ISSUE TITLE
请问可以使用零声母键吗

### ISSUE THREAD

**Issue by caiyuyux** [rimeinn/rime-moran#126]
首先我是个小白用户，没有很深入双拼的规则，有些表述可能不太准，请见谅。

我是从微软双拼转过来的，微软双拼的方案给我的感觉就是不是很准

偶然的机会看到了魔然，尝试了下发现挺不错的，打字准确度提高了不少，但是其中的有些按键不太习惯

比如 安  恩  这种零声母的词，按照魔然的方式，应该是 安 [a n]  恩 [e n]

但是个人觉得好像有点别扭，韵母被拆出来了

我比较习惯的是加上零声母键的打法，比如  安[a j]  恩[e f]  或者   安[o j]  恩[o f] 

请问是否可以通过配置的方式做到呢，万分感谢

**Comment by pfeiwu** [comment]
整句词库的双拼转换可以通过rime的拼写运算实现，不过固顶码表可能不太行，存在简码和无理码的干扰。

有代码能力的话还可以看看tools里提供的脚本schemagen.py，有转换词库双拼的功能，不过只实现了自然码和小鹤双拼，其他方案需要改改。
附文档地址
https://www.zrmfans.cn/book/tools/schemagen/

**Comment by ksqsf** [comment]
给一个配置例子吧。修改 `moran.yaml`，在 

```
lsm:  # 写到文件开头
  __append:
    - derive/an/oj/  # 原来的 oj 输出来自 moran_fixed.symbols.dict.yaml
    - derive/en/of/  # 同上
    # 补充其他自己想要的零声母映射规则

algebra:
  user_sentence_top:
    __append:
      __patch:
        # 其他已有的建议保留
        - :/lsm
```

![Image](https://github.com/user-attachments/assets/7938035b-3b8c-40a7-a806-cad77c67ef3e)

需要注意：
1. `o` 开头的码很多有特殊功能，或者在固顶码表里设置了符号（`moran_fixed.symbols.yaml`），可能会有所干扰。
2. 没有固定简码，需要手动修改 `moran_fixed(_simp).dict.yaml`。

不在乎的话是可以用的，可以先试试看。
