### ISSUE TITLE
切分轮换快捷键 Ctrl+L 是会和应用快捷键冲突吗？

### ISSUE THREAD

**Issue by ZhaJiMan** [rimeinn/rime-moran#134]
我看文档了给出了切分轮换快捷键 Ctrl+L，但是在文本编辑器和浏览器里都无法触发，会被应用的的同名快捷键覆盖。那如何让这个快捷键生效呢？同理切换简繁的 Ctrl+S 也是。我刚尝试用 rime，对配置还是不太了解。

**Comment by ksqsf** [comment]
这两个快捷键只在你有输入（有候选框）的时候才生效，所以理论上应该被输入法截获。

可否详细说明你的系统环境？

**Comment by ZhaJiMan** [comment]
- Windows 11 家庭中文版 24H2 26100.3915
- rime 官网安装的小狼毫 0.16.3
- `Moran-Simp-v2.0.2`，通过直接粘贴进用户目录安装
- 只使用了 `moran.custom.yaml` 进行配置

```yaml
patch:
  menu/page_size: 6
  switches/@0/reset: 1
  ascii_composer/switch_key:
    Shift_L: clear
    Shift_R: clear
  key_binder/bindings:
    - { when: has_menu, accept: Return, send: space }
    - { when: has_menu, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
  moran/enable_quick_code_hint: true
  moran/enable_aux_hint: true
  punctuator/full_shape:
    '\': '、'
    '@': '@'
    '#': '#'
  punctuator/half_shape:
    '\': '、'
    '@': '@'
    '#': '#'
```
